### ISSUE TITLE
Internal REG on or off? 

### ISSUE THREAD

**Issue by zubeer95** [c-/ESP32-Ethgate#1]
Hi, 
thanks for sharing this project. 
I was checking it and there is someting that seems to be a bit off, could you please help me to understand what I am missing? 

I can see from the schematic that VDDCR is left floating, thus I assume that you are using the internal regular of LAN8720A, however, the pin LED1/REGOFF is pulled up at VDD2A. 
From the datasheet, http://ww1.microchip.com/downloads/en/DeviceDoc/8720a.pdf section 3.7.3.1 it states:"To disable the +1.2V internal regulator, a pull-up strapping resistor should be connected from the REGOFF configuration strap to VDD2A".

So it is not clear if the internal regular is on or off in your solution, I believe that the correct design for that led should be as it is in section 3.8.1.1; 

Let me know what I am missing. 

Kind regards
Z.

**Comment by c-** [comment]
I think you're right. I cribbed that part of my schematic from another source without looking too deeply at the details.

Best theory as to why it still works (I have a bunch running, so it definitely works) is that 1.5K current limiting resistor on the LED. The datasheet and schematic checklist recommend something more like 300R, and there's a note in the schematic checklist about "Due to possible lower I/O voltages used on the LAN8720, lower strapping resistor values need to be used to ensure the strapped configuration is properly latched", so that 1.5K in tandem with the LED forward voltage drop (~1.8V for the LED's in that connector), the built-in pulldown might be enough to tip the balance towards "LOW" during power-on.

Well, I'll fix that. I was planning on doing an update soonish.

**Comment by zubeer95** [comment]
Great, I saw the same mistake in other projects online and some open-source mass-produced products. 
Better to update it to avoid further propagation of this error!

**Comment by c-** [comment]
I've pushed an updated version which should fix this problem, among other things. Untested at the moment. I'm firing off an oshpark order as my PCB mill is currently undergoing a controller cleanup.

**Comment by pd0wm** [comment]
I think your configuration is still a bit off. You're connecting `LED2/nINTSEL` to ground (via the LED). This configures your clock to `REF_CLK Out Mode` (`nIntsel = 0)`, which I think you don't want since the clock is supplied by the ESP32. You want to connect the LED to VDD to use `REF_CLK In Mode` (`nIntsel = 1`).  

Since you're missing the suggested 10k resistor it might still work by chance.


![2023-07-14-162121_840x411_scrot](https://github.com/c-/ESP32-Ethgate/assets/1314752/bfdb8952-6f0b-42cd-aa41-e8a4c7e7f29b)
![2023-07-14-162159_795x484_scrot](https://github.com/c-/ESP32-Ethgate/assets/1314752/1d6dd5bb-f60b-400b-b1ae-95caf74029f2)

**Comment by c-** [comment]
You're absolutely right, and I never even had a chance to assemble that last batch of boards. What you've described is how the Olimex ESP32-PoE board does it (with a LAN8710). I guess I need another spin...

**Comment by mihaipenica** [comment]
Hi , thank you for sharing this. Is there any chance you can also upload a version of your working code. 
My board is requesting dhcp IP from the router. The router offers the IP, but the device is not setting it. I have checked everything and am trying to figure out what might be the problem. 
Thank you!

**Comment by Gi-z** [comment]
+1, also having this same issue. Tested with both esp-idf and Arduino IDE's LAN_8720 example.

**Comment by c-** [comment]
I *finally* got around to bringing up a fixed (v2.4) board, and it seems quite happy now.
